//required fields:

//id (from supabase id
//username
//datecreated

//other fields
//avatarphoto
//contacts

//just borrow from model_large/chat_user but omit email.
//all fields of User will be used for conducting user searches.

import '../../singletons.dart';

class ChatUser {
  /// Uid generated by Supabase Auth. Only value is ''.
  final String uid;
  /// Name of user.
  final String username;
  /// Email address of user.
  final String signature;
  /// Image of Url, if not provided a default will be used.
  final String avatarUrl;
  /// Date of creation.
  final DateTime dateCreated;
  /// NEW: List of uids as contacts. Starts with null.
  final List<String> contacts;

  /// Constructor.
  ChatUser({
    required this.uid,
    required this.username,
    required this.signature,
    required this.avatarUrl,
    required this.dateCreated,
    required this.contacts
  });

  /// Converts a ChatUser2 object to a Map.
  Map<String, dynamic> toMap() {
    return {
      'uid': uid ?? '',
      'name': username,
      'signature': signature,
      'avatar_url': avatarUrl,
      'date_created': dateCreated.toIso8601String(),
      'contacts': contacts,
    };
  }

  static ChatUser fromMap(Map<String, dynamic> map) {
    return ChatUser(
      uid: map['uid'] as String,
      username: map['name'] as String,
      signature: map['signature'] as String ?? '',
      avatarUrl: map['avatarUrl'] as String ?? '',
      dateCreated: DateTime.parse(map['dateCreated'] as String),
      contacts: List<String>.from(map['contacts'] ?? []),
    );
  }
}