class ChatUser {
  //id auto-generated by Supabase
  final int? id;
  //name of user
  final String name;
  //status whether 'online', 'active' or 'offline'
  final String status;
  //data for one image, stored in Storage of Supabase, but I want it to be default null
  final List<int>? imageData;
  //Signature of a user, only in string form without emojis or images.
  final String signature;
  //Last time a user is 'online'. Automatically generated by Supabase when user is created or when existing user
  //logs off.
  final DateTime? lastSeen;
  //password encrypted.
  final String passwordHash;

  ChatUser({
    this.id,
    required this.name,
    this.status = 'offline',
    this.imageData,
    this.signature = '',
    this.lastSeen,
    required this.passwordHash,
  });
}
