class ChatMessage {
// id of message, automatically generated by postgres
  final int? id;

// id of sender, references to id in User class.
  final int senderId;

// text of message.
  final String messageText;

// list of all the emojis included in the message, can be null
  final List<String>? emojiList;

// list of all the files included in the message, can be null
  final List<String>? fileList;

// auto-generated by Supabase when a new entry is added to the table.
  final DateTime? timestamp;

// whether or not message has been deleted, default false.
  final bool deleted;

  ChatMessage({
    this.id,
    required this.senderId,
    this.messageText = '',
    this.emojiList,
    this.fileList,
    this.timestamp,
    this.deleted = false,
  });
}