class ChatRoom {
//id of room, automatically generated by Supabase.
  final int? id;
//type of room, can be either 'pm' or 'group'
  final String type;
//name of room, default value '', only fill if type == 'group'
  final String name;
//data for room image, stored in Storage of Supabase, but I want it to be default null, only fill if type == 'group'
  List<int>? imageData;
//list of all the id of Users in the room, references to id in User.
  final List<int> memberIds;
  //id of the last message, references to id in Message.
  final int lastMessageId;
//date the room is created, generated automatically by Supabase when a new room is written to the table.
  final DateTime? dateCreated;

  ChatRoom({
    this.id,
    required this.type,
    this.name = '',
    this.imageData,
    required this.memberIds,
    required this.lastMessageId,
    this.dateCreated,
  });
}